### ISSUE TITLE
A question about time complexity of L2 GCN

### ISSUE THREAD

**Issue by skyelves** [TAMU-VITA/L2-GCN#12]
In your paper, it says the time complexity of L-GCN is $O(L \frac{||Aˆ ||}{N_{BAT}} D + BD^2)$. The reason is that`For the time complexity, L-GCN only conducts FA L times in the entire training process and FT does once per batch.`

I was a little bit confused about how to get the correct time complexity and would appreciate it if you could help to answer the two questions below.
1. For the first part, why is $L ||Aˆ || D$ divided by $N_{BAT}$?
2. For the second part, according to the Figure2 in your paper, it seems it has to conduct FT once **per batch per layer**? so the time complexity is $LBD^2$ in that sense?

**Comment by yyou1996** [comment]
Hi @skyelves,

Sorry for the delayed reply. The detailed description is shown in Sec. 3.1. Two parts correspond to FA and FT, respectively. 
Considering we only train models for N_BAT batches. For Q1, L-GCN only performs FA once (per layer) versus once per batch in full-batch training (see Sec 2.1), i.e. 1: N_BAT. Since full-batch FA (per-batch) complexity is L||A||D, L_GCN takes L||A||D/N_BAT (that is, if you only train for one batch, then it barely won't save things). For Q2, the table shows per-batch complexity, and in each batch, L-GCN only needs to update the current layer (previous ones will freeze, which makes "layer-wise" comes from).

Hope it help.

**Comment by skyelves** [comment]
Hi @yyou1996 , Thanks for the clarification. `For Q2, the table shows per-batch complexity, and in each batch, L-GCN only needs to update the current layer (previous ones will freeze, which makes "layer-wise" comes from).` Just to be clear, for example, suppose we want to train a 5-layer model and we generate 50 batches, do we train each layer with 10 batches respectively? The reason I ask this question is that I think the overall complexity makes more sense than the per batch complexity since in full-batch train, it trains all layers and in L-GCN it trains one layer.

**Comment by yyou1996** [comment]
@skyelves yes in L-GCN, you need to adjust the batch number for each layer. 10 for each layer is an option.

**Comment by skyelves** [comment]
Thanks very much for clarification!
